"use client";
import React, { createContext, useContext, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import type { User as SupabaseUser } from "@supabase/supabase-js";
import { getSupabaseClient, isBrowserSupabaseConfigured } from "@/lib/supabase";
export interface User { name: string; email: string; role: "applicant" | "officer"; enterpriseId?: string; enterpriseName?: string; department?: string; isDigiLockerVerified?: boolean; phone?: string; panNumber?: string; entityType?: string; addressLine1?: string; addressLine2?: string; pinCode?: string; district?: string; state?: string; }
type Profile = Omit<User, "email" | "role">;
interface AuthContextType { user: User | null; isLoading: boolean; signIn: (email: string, password: string) => Promise<string | null>; signUpApplicant: (email: string, password: string, profile: Profile) => Promise<{ error: string | null; needsConfirmation: boolean }>; updateProfile: (profile: Partial<Profile>) => Promise<string | null>; loginWithDigiLocker: () => Promise<string>; logout: () => Promise<void>; }
const AuthContext = createContext<AuthContextType | undefined>(undefined);
const mapUser = (u: SupabaseUser): User => { const m = u.user_metadata ?? {}; return { name: m.name || m.full_name || u.email?.split("@")[0] || "AARAMBH User", email: u.email || "", role: m.role === "officer" ? "officer" : "applicant", enterpriseId: m.enterpriseId || u.id, enterpriseName: m.enterpriseName, department: m.department, isDigiLockerVerified: m.isDigiLockerVerified === true, phone: m.phone, panNumber: m.panNumber, entityType: m.entityType, addressLine1: m.addressLine1, addressLine2: m.addressLine2, pinCode: m.pinCode, district: m.district, state: m.state }; };
export function AuthProvider({ children }: { children: React.ReactNode }) { const [user, setUser] = useState<User | null>(null); const [isLoading, setIsLoading] = useState(isBrowserSupabaseConfigured); const router = useRouter(); useEffect(() => { localStorage.removeItem("aarambh_user"); const s = getSupabaseClient(); if (!s) return; void s.auth.getUser().then(({ data }) => { setUser(data.user ? mapUser(data.user) : null); setIsLoading(false); }); const { data: { subscription } } = s.auth.onAuthStateChange((_e, session) => { setUser(session?.user ? mapUser(session.user) : null); setIsLoading(false); }); return () => subscription.unsubscribe(); }, []); const signIn = async (email: string, password: string) => { const s = getSupabaseClient(); if (!s) return "Authentication is not configured for this environment."; const { error } = await s.auth.signInWithPassword({ email, password }); return error ? "Unable to sign in with those credentials." : null; }; const signUpApplicant = async (email: string, password: string, profile: Profile) => { const s = getSupabaseClient(); if (!s) return { error: "Authentication is not configured for this environment.", needsConfirmation: false }; const { data, error } = await s.auth.signUp({ email, password, options: { data: { ...profile, role: "applicant" } } }); return { error: error?.message ?? null, needsConfirmation: !error && !data.session }; }; const updateProfile = async (profile: Partial<Profile>) => { const s = getSupabaseClient(); if (!s) return "Authentication is not configured for this environment."; const { error } = await s.auth.updateUser({ data: profile }); return error?.message ?? null; }; const loginWithDigiLocker = async () => "DigiLocker sign-in is not configured. Please use your AARAMBH credentials."; const logout = async () => { const s = getSupabaseClient(); if (s) await s.auth.signOut(); setUser(null); router.push("/signin"); }; return <AuthContext.Provider value={{ user, isLoading, signIn, signUpApplicant, updateProfile, loginWithDigiLocker, logout }}>{children}</AuthContext.Provider>; }
export function useAuth() { const c = useContext(AuthContext); if (!c) throw new Error("useAuth must be used within an AuthProvider"); return c; }
